version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - cd serverless
      - npm install
      - npm install serverless -g
      - serverless -v
      - ls
  build:
    commands: 
      - serverless deploy --stage dev     